language: node_js
node_js:
    - "6"
    - "7"
    - "8"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
after_script:
    - npm run coverall
    - bash <(curl -s https://codecov.io/bash)
deploy:
    provider: npm
    email: tony.li@vechain.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
        tags: true
        node: '8'
